### ISSUE TITLE
this app location "atomic-wiki` (new) vs "wiki"

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/AtomicWiki#67]
this app now installs to `apps/atomic-wiki/` the old app to `apps/wiki/` so a lot of links are now broken. See `/apps/atomic-wiki/data/WikiIntro.html` it no longer has styling for probably the same reason. Obviously the repo target is `<target>/db/wiki</target>`???

_Originally posted by @duncdrum in https://github.com/eXist-db/AtomicWiki/pull/59_

**Comment by adamretter** [comment]
You can either change just the `target` here - https://github.com/eXist-db/AtomicWiki/blob/master/xar-assembly.xml#L27 or you could change the `package-abbrev` here - https://github.com/eXist-db/exist-apps-parent/blob/master/pom.xml#L63

As it has been `atomic-wiki` in the parent pom.xml for some time now, I am not sure why things are breaking exactly?

**Comment by joewiz** [comment]
Closed in https://github.com/eXist-db/AtomicWiki/commit/79702c1ab1e49c8ba238d66ad61989b130c1aea3 - using the 1st option from @adamretter's suggestion, and mirroring the approach used in exist-documentation.
